[improve] review filebased backup/restore

diff --git a/templates/common-shfuncs.sh.j2 b/templates/common-shfuncs.sh.j2
--- a/templates/common-shfuncs.sh.j2
+++ b/templates/common-shfuncs.sh.j2
@@ -1,7 +1,7 @@
 
 logmsg() {
     _msg=$*
-    echo $_msg
+    [ -n "$VERBOSE" ] && echo $_msg
     [ -n "$LOGFILE" ] && echo $_msg >>$LOGFILE
     [ -n "$SYSLOG" ]  && logger -t exist-filebased-backup $_msg
 }
@@ -10,9 +10,36 @@ logerr() {
     _excode=$1
     shift
     _msg=$*
-    echo $_msg >&2
+    [ -n "$VERBOSE" ] && echo $_msg >&2
     [ -n "$LOGFILE" ] && echo $_msg >>$LOGFILE
     [ -n "$SYSLOG"  ] && logger -t exist-filebased-backup -p error $_msg
     echo "exiting, logfile $LOGFILE" >&2
     exit $_excode
+}
+
+ask_stop() {
+    if [ -z "$FORCE" ]; then
+	echo -n "This will STOP the exist instance before doing the backup. Proceed? [yN] "
+	read proceed
+	case "$proceed" in
+	    y|Y) :;;
+	    *) logerr 1 "Aborted by user"; exit 1;;
+	esac
+    fi
+}
+
+# if eXist instance is running, stop it first
+shutdown_exist() {
+    if psexist -S $INSTNAME | grep -q "instance: $INSTNAME"; then
+        ask_stop
+	logmsg "Stopping running eXist instance \"${INSTNAME}\""
+	service ${INSTNAME} stop
+	# check again to verify it is really dead, just to be sure
+	sleep $DEAD_CHECK_SLEEP
+	if psexist -S $INSTNAME | grep -q "instance: $INSTNAME"; then
+	    logerr 2 "ERROR: eXist instance \"${INSTNAME}\" still running after stop command"
+	fi
+    else
+	logmsg "eXist instance \"${INSTNAME}\" not running"
+    fi
 }
